//
//  AffirmationCatalog.swift
//  Daily AI Affirmations
//
//  Created by Codex.
//

import Foundation

enum AffirmationCatalog {
    static let spanish: [String] = [
        "Hoy elijo la calma y la claridad.",
        "Confío en mi proceso paso a paso.",
        "Merezco descansar y recargar energía.",
        "Mi mente puede aprender algo nuevo hoy.",
        "Me permito avanzar a mi propio ritmo.",
        "Respiro profundo y suelto la tensión.",
        "Soy constante y eso me fortalece.",
        "Mi esfuerzo de hoy construye mi futuro.",
        "Tengo la capacidad de resolver lo importante.",
        "Atraigo oportunidades alineadas con mis valores.",
        "Mi creatividad fluye con facilidad.",
        "Hoy cuido mi cuerpo con cariño.",
        "Puedo pedir ayuda cuando la necesito.",
        "Soy amable conmigo misma/o.",
        "Cada paso pequeño cuenta.",
        "Mi enfoque crea resultados.",
        "Elijo pensamientos que me apoyan.",
        "Estoy presente y en paz.",
        "Mi voz merece ser escuchada.",
        "Acepto el progreso, no la perfección.",
        "Confío en mi intuición.",
        "Mi energía es valiosa y la administro bien.",
        "Soy capaz de adaptarme a los cambios.",
        "Me abro a nuevas posibilidades.",
        "Tengo disciplina y corazón.",
        "Mi paciencia es una fortaleza.",
        "Hoy honro mis límites.",
        "Mis decisiones reflejan mi bienestar.",
        "Me permito disfrutar el momento.",
        "Mi gratitud me abre caminos.",
        "Estoy aprendiendo y creciendo cada día.",
        "Soy suficiente tal como soy.",
        "Mi trabajo tiene propósito.",
        "Puedo comenzar de nuevo cuando lo necesite.",
        "Elijo la valentía sobre el miedo.",
        "Mi mente es clara y enfocada.",
        "Doy lo mejor de mí con tranquilidad.",
        "Mis ideas son valiosas.",
        "Mi corazón guía mis acciones.",
        "Confío en mi capacidad de crear hábitos sanos.",
        "Hoy me trato con respeto.",
        "Soy resiliente y puedo con esto.",
        "Merezco relaciones que me cuiden.",
        "Mi paz interior es mi prioridad.",
        "Puedo lograr cosas importantes con constancia.",
        "Acepto lo que no puedo controlar.",
        "Elijo una actitud abierta y positiva.",
        "Mi descanso también es productividad.",
        "Mi voz interna es amable.",
        "Hoy elijo el equilibrio.",
        "Me permito celebrar mis avances.",
        "Estoy rodeada/o de apoyo.",
        "Mi enfoque es gentil y firme.",
        "Soy capaz de aprender de mis errores.",
        "Mi tiempo es valioso.",
        "Hoy me doy permiso de brillar.",
        "Mi curiosidad me impulsa.",
        "Soy flexible y adaptable.",
        "Puedo concentrarme en lo esencial.",
        "La calma me acompaña.",
        "Confío en el ritmo natural de la vida.",
        "Mi bienestar es una elección diaria.",
        "Estoy haciendo lo correcto para mí.",
        "Mi creatividad encuentra soluciones.",
        "Elijo palabras que me elevan.",
        "Soy fuerte y serena/o.",
        "Mi corazón está en paz.",
        "Puedo terminar lo que empiezo.",
        "Hoy reconozco mi valor.",
        "Mi trabajo mejora con práctica.",
        "Merezco cosas buenas.",
        "Estoy en el camino correcto.",
        "Mi amabilidad crea conexiones.",
        "Elijo cuidar mi energía.",
        "Hoy mi mente está tranquila.",
        "Mis sueños merecen mi atención.",
        "Me permito avanzar con confianza.",
        "Soy digno/a de éxito.",
        "Mi presencia es un regalo.",
        "Puedo tomar decisiones sabias.",
        "Hoy elijo la gratitud.",
        "Mi esfuerzo está dando frutos.",
        "Elijo aprender en lugar de juzgar.",
        "Mi equilibrio emocional crece.",
        "Confío en mis habilidades.",
        "Mi futuro se construye con amor.",
        "Hoy suelto lo que me pesa.",
        "Soy luz para mí y para otros.",
        "Mi mente es un lugar seguro.",
        "Merezco sentirme en paz.",
        "Hoy, {name}, eliges cuidarte.",
        "{name}, tu constancia te llevará lejos.",
        "Respira, {name}, lo estás haciendo bien.",
        "Hoy, {name}, confías en tu camino.",
        "{name}, tu voz importa.",
        "Tu calma inspira, {name}.",
        "{name}, mereces descanso y alegría.",
        "Paso a paso, {name}, estás creciendo.",
        "{name}, tu esfuerzo cuenta.",
        "{name}, hoy eliges tu bienestar.",
        "Me amo y me acepto profunda e incondicionalmente.",
        "Soy suficiente tal como soy ahora mismo.",
        "Merezco todo el amor y el respeto del mundo.",
        "Mi valor no depende de la opinión de los demás.",
        "Cada día me trato con más cariño y comprensión.",
        "Soy una persona valiosa y digna de cosas buenas.",
        "Mi autoestima crece y se fortalece cada día.",
        "Me perdono fácilmente y libero el pasado.",
        "Tengo derecho a poner límites sanos.",
        "Celebro mis logros, por pequeños que parezcan.",
        "Soy digno/a de recibir abundancia en todas sus formas.",
        "Mi cuerpo es mi hogar y lo cuido con amor.",
        "Me siento cómodo/a siendo yo mismo/a.",
        "Mi opinión sobre mí misma es la que más importa.",
        "Irradio confianza y seguridad desde dentro.",
        "Acepto mis imperfecciones con ternura.",
        "Soy una obra en constante evolución hermosa.",
        "Me respeto profundamente en cada decisión.",
        "Mi presencia aporta luz al mundo.",
        "Me permito brillar sin pedir permiso.",
        "Soy valioso/a solo por existir.",
        "Me hablo con palabras amables y pacientes.",
        "Mi autoestima es sólida e inquebrantable.",
        "Me elijo a mí primero, siempre con amor.",
        "Mi valor intrínseco nunca disminuye.",
        "Me siento orgulloso/a de quien estoy convirtiéndome.",
        "Me merezco descansar y disfrutar la vida.",
        "Mi energía es magnética y positiva.",
        "Soy digno/a de ser tratado/a con respeto.",
        "Me acepto completa/o con todas mis luces y sombras.",
        "Mi amor propio crece cada mañana.",
        "Me siento a gusto en mi propia piel.",
        "Soy fuerte, resiliente y valiente.",
        "Me permito sentir y expresar todas mis emociones.",
        "Mi autoestima no depende de logros externos.",
        "Me celebro todos los días.",
        "Soy una persona interesante y digna de conocer.",
        "Me trato con la misma dulzura que daría a mi mejor amigo.",
        "Mi valor es inmenso e infinito.",
        "Me amo más hoy que ayer.",
        "Soy merecedor/a de una vida plena y feliz.",
        "Mi opinión de mí misma es cada vez más amorosa.",
        "Me siento segura/o siendo auténtico/a.",
        "Mi autoestima se renueva y fortalece constantemente.",
        "Soy digna/o de recibir cumplidos y amor.",
        "Me respeto profundamente en todo momento.",
        "Mi luz interior nunca se apaga.",
        "Me siento completa/o y en paz conmigo misma/o.",
        "Soy un ser único y maravilloso.",
        "Me amo incondicionalmente, hoy y siempre.",
        "El dinero llega a mí de formas esperadas e inesperadas.",
        "Vivo en un estado permanente de abundancia.",
        "Atraigo oportunidades económicas excelentes.",
        "Merezco ganar dinero haciendo lo que amo.",
        "Mi relación con el dinero es sana y positiva.",
        "El universo siempre me provee todo lo que necesito.",
        "Fluyo con la prosperidad en todos los niveles.",
        "Soy un imán para la riqueza y la abundancia.",
        "Recibo dinero con gratitud y alegría.",
        "Mi vida está llena de recursos ilimitados.",
        "Atraigo clientes ideales con facilidad.",
        "El éxito financiero es mi estado natural.",
        "Siempre hay más que suficiente para mí y para compartir.",
        "Mi valor aumenta y mi ingreso también.",
        "Disfruto manejando el dinero con inteligencia.",
        "La abundancia fluye hacia mí en grandes cantidades.",
        "Soy digno/a de una riqueza creciente y constante.",
        "Encuentro soluciones creativas para generar prosperidad.",
        "El dinero trabaja para mí mientras duermo.",
        "Vivo en gratitud por toda la riqueza que ya tengo.",
        "Atraigo colaboraciones lucrativas y placenteras.",
        "Mi mente está abierta a nuevas formas de ganar dinero.",
        "La prosperidad es mi derecho de nacimiento.",
        "Recibo bendiciones económicas todos los días.",
        "Mi vida es abundante en amor, salud y dinero.",
        "Confío plenamente en la provisión universal.",
        "Soy un canal abierto para la riqueza infinita.",
        "El dinero llega a mí fácil y constantemente.",
        "Celebro cada aumento en mi prosperidad.",
        "Vivo en un círculo virtuoso de abundancia.",
        "Atraigo ideas millonarias con facilidad.",
        "Mi cuenta bancaria crece con alegría.",
        "Merezco una vida económicamente libre.",
        "El éxito financiero me persigue a mí.",
        "Soy generoso/a porque siempre recibo más.",
        "La riqueza se siente natural y cómoda para mí.",
        "Agradezco el dinero que ya tengo y el que viene.",
        "Mi energía vibra en frecuencia de abundancia.",
        "Vivo rodeado/a de oportunidades prósperas.",
        "El dinero fluye hacia mí desde múltiples fuentes.",
        "Soy próspero/a en todos los aspectos de mi vida.",
        "Disfruto la libertad financiera que merezco.",
        "Mi mente está programada para la riqueza.",
        "Atraigo socios, proyectos y dinero con facilidad.",
        "Vivo en gratitud constante por mi prosperidad.",
        "El universo conspira a mi favor económicamente.",
        "Soy un imán poderoso para el dinero positivo.",
        "Mi vida es una demostración de abundancia.",
        "Recibo riqueza con manos y corazón abiertos.",
        "Soy próspero/a, abundante y libre.",
        "Mi cuerpo está sano, fuerte y lleno de vitalidad.",
        "Cada célula de mi cuerpo se regenera perfectamente.",
        "Me despierto cada mañana lleno/a de energía.",
        "Cuido mi cuerpo con amor y respeto.",
        "Mi sistema inmunológico es poderoso y eficiente.",
        "Mi mente y mi cuerpo están en perfecta armonía.",
        "Elijo alimentos que nutren y me hacen sentir bien.",
        "Duermo profundamente y me despierto renovado/a.",
        "Mi respiración es profunda, calmada y sanadora.",
        "Mi cuerpo sabe exactamente cómo sanarse.",
        "Irradio salud y vitalidad por donde voy.",
        "Me siento ligero/a, lleno/a de energía y feliz.",
        "Mi corazón late fuerte y saludable.",
        "Cada día mi salud mejora notablemente.",
        "Agradezco a mi cuerpo por todo lo que hace por mí.",
        "Mi energía es alta, constante y positiva.",
        "Me recupero rápidamente de cualquier malestar.",
        "Mi postura es erguida y mi cuerpo relajado.",
        "Vivo en un estado de bienestar total.",
        "Mi mente está clara y mi cuerpo ligero.",
        "Me muevo con gracia y facilidad.",
        "Mi piel brilla de salud y vitalidad.",
        "Elijo pensamientos que sanan mi cuerpo.",
        "Mi sistema nervioso está calmado y equilibrado.",
        "Tengo una salud inquebrantable.",
        "Mi cuerpo es mi templo y lo honro diariamente.",
        "Me lleno de energía sanadora cada mañana.",
        "Mi vitalidad aumenta día tras día.",
        "Vivo con un cuerpo sano y una mente serena.",
        "Cada célula vibra con vida y salud.",
        "Me siento fuerte, flexible y lleno/a de vida.",
        "Mi cuerpo responde positivamente a mi amor.",
        "Duermo como bebé y despierto lleno/a de energía.",
        "Mi salud es mi mayor riqueza.",
        "Me siento rejuvenecido/a y lleno/a de vida.",
        "Mi organismo funciona en perfecta armonía.",
        "Irradio salud desde el interior hacia fuera.",
        "Elijo hábitos que potencian mi bienestar.",
        "Mi cuerpo se siente joven y lleno de fuerza.",
        "Agradezco mi excelente estado de salud.",
        "Mi energía vital es abundante e inagotable.",
        "Vivo en un cuerpo sano y feliz.",
        "Cada respiración me llena de salud.",
        "Mi cuerpo se renueva mientras descanso.",
        "Me siento en el mejor momento de mi salud.",
        "Mi vitalidad es contagiosa y positiva.",
        "Cuido mi salud física, mental y emocional.",
        "Mi cuerpo me da señales claras y las escucho.",
        "Vivo con un nivel de energía altísimo.",
        "Soy salud, fuerza y vitalidad en movimiento.",
        "Mi mente está en paz en todo momento.",
        "Elijo pensamientos que me traen serenidad.",
        "Me mantengo tranquilo/a pase lo que pase.",
        "Libero fácilmente todo lo que no me sirve.",
        "Vivo en un estado de calma profunda.",
        "Mi corazón está en paz y lleno de amor.",
        "Respira paz, exhala tranquilidad.",
        "Nada ni nadie perturba mi paz interior.",
        "Me siento seguro/a y protegido/a siempre.",
        "Mi mente está clara, tranquila y enfocada.",
        "Acepto lo que no puedo cambiar con serenidad.",
        "Me rodeo de una burbuja de paz constante.",
        "Mi interior es un refugio de calma absoluta.",
        "Libero el estrés y abrazo la tranquilidad.",
        "Vivo el presente con total presencia y paz.",
        "Mi energía es serena y equilibrada.",
        "Me siento en paz conmigo mismo/a y con el mundo.",
        "Todo está bien en mi mundo ahora mismo.",
        "Mi mente descansa en un silencio amoroso.",
        "Elijo la paz en cada situación.",
        "Mi alma está en calma profunda y permanente.",
        "Libero preocupaciones y abrazo la tranquilidad.",
        "Vivo con el corazón ligero y la mente en paz.",
        "La serenidad es mi estado natural.",
        "Me siento protegido/a por una paz infinita.",
        "Mi respiración me lleva siempre a la calma.",
        "Nada puede quitarme mi paz interior.",
        "Vivo relajado/a, confiado/a y en armonía.",
        "Mi mente está libre de ruido y en calma.",
        "Elijo respuestas tranquilas y sabias.",
        "Mi paz interior crece cada día.",
        "Me siento en completo equilibrio emocional.",
        "La tranquilidad fluye por todo mi ser.",
        "Vivo desde un lugar de profunda serenidad.",
        "Libero el control y abrazo la paz.",
        "Mi corazón late tranquilo y contento.",
        "Estoy en paz con el pasado, presente y futuro.",
        "Mi mente es un lago sereno y cristalino.",
        "La calma es mi superpoder.",
        "Me siento seguro/a, tranquilo/a y en paz.",
        "Elijo pensamientos que nutren mi serenidad.",
        "Mi paz no depende de circunstancias externas.",
        "Vivo en un estado constante de bienestar.",
        "Mi alma respira paz en cada momento.",
        "Me permito descansar en la tranquilidad.",
        "Todo se resuelve con calma y sabiduría.",
        "Mi interior es un santuario de paz.",
        "Me siento ligero/a, calmado/a y feliz.",
        "La paz fluye por cada célula de mi ser.",
        "Vivo en armonía total conmigo y con la vida.",
        "Cada día me convierto en la mejor versión de mí.",
        "Atraigo experiencias que me hacen crecer.",
        "Confío plenamente en mi camino y timing.",
        "Tengo todo lo necesario para tener éxito.",
        "Mis sueños se materializan con facilidad.",
        "Soy valiente y doy pasos firmes hacia mis metas.",
        "El éxito me encuentra porque voy hacia él.",
        "Aprendo con alegría de cada experiencia.",
        "Mi vida mejora en todas las áreas constantemente.",
        "Soy magnético/a para las oportunidades perfectas.",
        "Creo resultados extraordinarios con facilidad.",
        "Confío en mi intuición y en mis decisiones.",
        "Mi vida es una aventura hermosa y emocionante.",
        "Me abro a recibir todo lo bueno que merezco.",
        "Cada día es una nueva oportunidad de brillar.",
        "Vivo con propósito, pasión y alegría.",
        "Todo lo que necesito llega en el momento perfecto.",
        "Soy un ser creativo, poderoso y lleno de talento.",
        "Mis metas se cumplen con gracia y fluidez.",
        "Me siento realizado/a y profundamente feliz.",
        "El universo siempre está de mi lado.",
        "Vivo una vida plena, auténtica y significativa.",
        "Atraigo relaciones sanas y enriquecedoras.",
        "Mi energía positiva transforma mi realidad.",
        "Soy libre para crear la vida de mis sueños.",
        "Cada desafío me hace más fuerte y sabio/a.",
        "Mi futuro es brillante, abundante y feliz.",
        "Me permito soñar en grande y lograrlo.",
        "Vivo con gratitud y maravilla cada día.",
        "Soy un imán para milagros cotidianos.",
        "Mi vida fluye con facilidad y alegría.",
        "Confío en que todo trabaja a mi favor.",
        "Me siento apoyado/a por el universo entero.",
        "Creo belleza, amor y abundancia donde voy.",
        "Mi potencial es ilimitado y lo estoy usando.",
        "{name}, eres infinitamente valioso/a y amado/a tal como eres.",
        "Cada día {name} te aceptas más y te quieres más profundamente.",
        "{name}, mereces una vida llena de alegría, amor y abundancia.",
        "El universo siempre conspira a favor de {name}.",
        "{name}, tu luz interior brilla cada vez más fuerte.",
        "{name}, confías plenamente en tu intuición y en tus decisiones.",
        "Todo lo que {name} necesita ya está llegando a su vida.",
        "{name}, eres fuerte, resiliente y capaz de superar cualquier reto.",
        "La paz y la calma habitan permanentemente en el corazón de {name}.",
        "{name}, atraes personas y oportunidades que te elevan.",
        "Cada mañana {name} se despierta lleno/a de energía y gratitud.",
        "{name}, tu autoestima crece y se fortalece con cada respiración.",
        "El éxito y la prosperidad persiguen naturalmente a {name}.",
        "{name}, te perdonas con facilidad y liberas todo el pasado.",
        "Tu cuerpo y tu mente están en perfecta armonía, {name}.",
        "{name}, eres digno/a de recibir amor incondicional todos los días.",
        "La abundancia fluye hacia {name} de formas inesperadas y maravillosas.",
        "{name}, cada paso que das te acerca a tu versión más plena.",
        "La felicidad es el estado natural de {name}.",
        "{name}, irradias confianza, carisma y magnetismo positivo.",
        "Todo conspira para que {name} viva su mejor vida posible.",
        "{name}, te permites soñar en grande y ves cómo se hacen realidad.",
        "La salud, la vitalidad y la fuerza acompañan siempre a {name}.",
        "{name}, eres un ser único, irrepetible y absolutamente valioso.",
        "Cada desafío fortalece y hace brillar más a {name}.",
        "{name}, vives en un estado permanente de gratitud y maravilla.",
        "El amor propio de {name} es profundo, sólido e inquebrantable.",
        "{name}, mereces y recibes respeto, cariño y admiración.",
        "Tu vida mejora en todos los aspectos cada día que pasa, {name}.",
        "{name}, eres la versión más elevada y auténtica de ti mismo/a."
    ]

    static let english: [String] = [
        "Today I choose calm and clarity.",
        "I trust my process step by step.",
        "I deserve rest and renewal.",
        "My mind can learn something new today.",
        "I allow myself to move at my own pace.",
        "I breathe deeply and release tension.",
        "Consistency strengthens me.",
        "My effort today builds my future.",
        "I can handle what matters.",
        "Opportunities aligned with my values find me.",
        "My creativity flows with ease.",
        "Today I care for my body with kindness.",
        "I can ask for help when I need it.",
        "I am gentle with myself.",
        "Every small step counts.",
        "My focus creates results.",
        "I choose thoughts that support me.",
        "I am present and at peace.",
        "My voice deserves to be heard.",
        "I honor progress over perfection.",
        "I trust my intuition.",
        "My energy is valuable and I use it wisely.",
        "I adapt to change with grace.",
        "I open myself to new possibilities.",
        "I have discipline and heart.",
        "My patience is a strength.",
        "Today I honor my boundaries.",
        "My choices reflect my well-being.",
        "I allow myself to enjoy the moment.",
        "Gratitude opens doors for me.",
        "I am learning and growing every day.",
        "I am enough exactly as I am.",
        "My work has purpose.",
        "I can begin again whenever I need to.",
        "I choose courage over fear.",
        "My mind is clear and focused.",
        "I give my best with ease.",
        "My ideas are valuable.",
        "My heart guides my actions.",
        "I trust my ability to build healthy habits.",
        "Today I treat myself with respect.",
        "I am resilient and I can do this.",
        "I deserve relationships that care for me.",
        "My inner peace is my priority.",
        "I can achieve important things with consistency.",
        "I accept what I cannot control.",
        "I choose an open and positive attitude.",
        "My rest is also productive.",
        "My inner voice is kind.",
        "Today I choose balance.",
        "I allow myself to celebrate my progress.",
        "I am supported.",
        "My focus is gentle and steady.",
        "I can learn from my mistakes.",
        "My time is valuable.",
        "Today I give myself permission to shine.",
        "My curiosity moves me forward.",
        "I am flexible and adaptable.",
        "I can concentrate on what matters most.",
        "Calmness is with me.",
        "I trust the natural rhythm of life.",
        "My well-being is a daily choice.",
        "I am doing what is right for me.",
        "My creativity finds solutions.",
        "I choose words that lift me up.",
        "I am strong and serene.",
        "My heart is at peace.",
        "I can finish what I start.",
        "Today I recognize my worth.",
        "My work improves with practice.",
        "I deserve good things.",
        "I am on the right path.",
        "My kindness creates connection.",
        "I choose to protect my energy.",
        "Today my mind is calm.",
        "My dreams deserve my attention.",
        "I allow myself to move forward with confidence.",
        "I am worthy of success.",
        "My presence is a gift.",
        "I can make wise decisions.",
        "Today I choose gratitude.",
        "My effort is paying off.",
        "I choose to learn instead of judge.",
        "My emotional balance grows.",
        "I trust my abilities.",
        "My future is built with love.",
        "Today I release what weighs me down.",
        "I am light for myself and others.",
        "My mind is a safe place.",
        "I deserve to feel at peace.",
        "Today, {name}, you choose to care for yourself.",
        "{name}, your consistency will take you far.",
        "Breathe, {name}, you are doing well.",
        "Today, {name}, you trust your path.",
        "{name}, your voice matters.",
        "Your calm inspires, {name}.",
        "{name}, you deserve rest and joy.",
        "Step by step, {name}, you are growing.",
        "{name}, your effort counts.",
        "{name}, today you choose your well-being.",
        "I love and accept myself deeply and unconditionally.",
        "I am enough exactly as I am right now.",
        "I deserve all the love and respect in the world.",
        "My worth does not depend on other people's opinions.",
        "Every day I treat myself with more kindness and understanding.",
        "I am a valuable person worthy of good things.",
        "My self-esteem grows and strengthens every day.",
        "I easily forgive myself and release the past.",
        "I have the right to set healthy boundaries.",
        "I celebrate my achievements, no matter how small they seem.",
        "I am worthy of receiving abundance in all its forms.",
        "My body is my home and I care for it with love.",
        "I feel comfortable being myself.",
        "My opinion of myself is the one that matters most.",
        "I radiate confidence and security from within.",
        "I accept my imperfections with tenderness.",
        "I am a beautiful work in constant evolution.",
        "I deeply respect myself in every decision.",
        "My presence brings light to the world.",
        "I allow myself to shine without asking permission.",
        "I am valuable simply because I exist.",
        "I speak to myself with kind and patient words.",
        "My self-esteem is solid and unbreakable.",
        "I choose myself first, always with love.",
        "My intrinsic value never decreases.",
        "I feel proud of who I am becoming.",
        "I deserve to rest and enjoy life.",
        "My energy is magnetic and positive.",
        "I am worthy of being treated with respect.",
        "I accept myself completely with all my lights and shadows.",
        "My self-love grows every morning.",
        "I feel comfortable in my own skin.",
        "I am strong, resilient, and courageous.",
        "I allow myself to feel and express all my emotions.",
        "My self-esteem does not depend on external achievements.",
        "I celebrate myself every day.",
        "I am an interesting person worthy of being known.",
        "I treat myself with the same sweetness I would give my best friend.",
        "My value is immense and infinite.",
        "I love myself more today than yesterday.",
        "I am deserving of a full and happy life.",
        "My opinion of myself becomes more loving every day.",
        "I feel safe being authentic.",
        "My self-esteem renews and strengthens constantly.",
        "I am worthy of receiving compliments and love.",
        "I deeply respect myself at all times.",
        "My inner light never fades.",
        "I feel complete and at peace with myself.",
        "I am a unique and wonderful being.",
        "I love myself unconditionally, today and always.",
        "Money comes to me in expected and unexpected ways.",
        "I live in a permanent state of abundance.",
        "I attract excellent economic opportunities.",
        "I deserve to earn money doing what I love.",
        "My relationship with money is healthy and positive.",
        "The universe always provides everything I need.",
        "I flow with prosperity on all levels.",
        "I am a magnet for wealth and abundance.",
        "I receive money with gratitude and joy.",
        "My life is full of unlimited resources.",
        "I attract ideal clients with ease.",
        "Financial success is my natural state.",
        "There is always more than enough for me and to share.",
        "My value increases and so does my income.",
        "I enjoy managing money intelligently.",
        "Abundance flows to me in large quantities.",
        "I am worthy of ever-growing and constant wealth.",
        "I find creative solutions to generate prosperity.",
        "Money works for me while I sleep.",
        "I live in gratitude for all the wealth I already have.",
        "I attract lucrative and enjoyable collaborations.",
        "My mind is open to new ways of earning money.",
        "Prosperity is my birthright.",
        "I receive economic blessings every day.",
        "My life is abundant in love, health, and money.",
        "I fully trust in universal provision.",
        "I am an open channel for infinite wealth.",
        "Money comes to me easily and constantly.",
        "I celebrate every increase in my prosperity.",
        "I live in a virtuous circle of abundance.",
        "I attract millionaire ideas with ease.",
        "My bank account grows with joy.",
        "I deserve an economically free life.",
        "Financial success chases me.",
        "I am generous because I always receive more.",
        "Wealth feels natural and comfortable to me.",
        "I am grateful for the money I have and the money coming.",
        "My energy vibrates at the frequency of abundance.",
        "I live surrounded by prosperous opportunities.",
        "Money flows to me from multiple sources.",
        "I am prosperous in every aspect of my life.",
        "I enjoy the financial freedom I deserve.",
        "My mind is programmed for wealth.",
        "I attract partners, projects, and money with ease.",
        "I live in constant gratitude for my prosperity.",
        "The universe conspires in my economic favor.",
        "I am a powerful magnet for positive money.",
        "My life is a demonstration of abundance.",
        "I receive wealth with open hands and heart.",
        "I am prosperous, abundant, and free.",
        "My body is healthy, strong, and full of vitality.",
        "Every cell in my body regenerates perfectly.",
        "I wake up every morning full of energy.",
        "I care for my body with love and respect.",
        "My immune system is powerful and efficient.",
        "My mind and body are in perfect harmony.",
        "I choose foods that nourish me and make me feel good.",
        "I sleep deeply and wake up renewed.",
        "My breathing is deep, calm, and healing.",
        "My body knows exactly how to heal itself.",
        "I radiate health and vitality wherever I go.",
        "I feel light, full of energy, and happy.",
        "My heart beats strong and healthy.",
        "Every day my health improves noticeably.",
        "I thank my body for everything it does for me.",
        "My energy is high, constant, and positive.",
        "I recover quickly from any discomfort.",
        "My posture is upright and my body relaxed.",
        "I live in a state of total well-being.",
        "My mind is clear and my body light.",
        "I move with grace and ease.",
        "My skin glows with health and vitality.",
        "I choose thoughts that heal my body.",
        "My nervous system is calm and balanced.",
        "I have unbreakable health.",
        "My body is my temple and I honor it daily.",
        "I fill myself with healing energy every morning.",
        "My vitality increases day by day.",
        "I live with a healthy body and a serene mind.",
        "Every cell vibrates with life and health.",
        "I feel strong, flexible, and full of life.",
        "My body responds positively to my love.",
        "I sleep like a baby and wake up full of energy.",
        "My health is my greatest wealth.",
        "I feel rejuvenated and full of life.",
        "My organism functions in perfect harmony.",
        "I radiate health from the inside out.",
        "I choose habits that enhance my well-being.",
        "My body feels young and full of strength.",
        "I am grateful for my excellent state of health.",
        "My vital energy is abundant and inexhaustible.",
        "I live in a healthy and happy body.",
        "Every breath fills me with health.",
        "My body renews itself while I rest.",
        "I feel at the best moment of my health.",
        "My vitality is contagious and positive.",
        "I care for my physical, mental, and emotional health.",
        "My body gives me clear signals and I listen to them.",
        "I live with a very high level of energy.",
        "I am health, strength, and vitality in motion.",
        "My mind is at peace at all times.",
        "I choose thoughts that bring me serenity.",
        "I remain calm no matter what happens.",
        "I easily release everything that no longer serves me.",
        "I live in a state of deep calm.",
        "My heart is at peace and full of love.",
        "I breathe peace, I exhale tranquility.",
        "Nothing and no one disturbs my inner peace.",
        "I always feel safe and protected.",
        "My mind is clear, calm, and focused.",
        "I accept what I cannot change with serenity.",
        "I surround myself with a constant bubble of peace.",
        "My interior is a refuge of absolute calm.",
        "I release stress and embrace tranquility.",
        "I live in the present with total presence and peace.",
        "My energy is serene and balanced.",
        "I feel at peace with myself and with the world.",
        "Everything is well in my world right now.",
        "My mind rests in loving silence.",
        "I choose peace in every situation.",
        "My soul is in deep and permanent calm.",
        "I release worries and embrace tranquility.",
        "I live with a light heart and a peaceful mind.",
        "Serenity is my natural state.",
        "I feel protected by infinite peace.",
        "My breathing always takes me to calm.",
        "Nothing can take away my inner peace.",
        "I live relaxed, confident, and in harmony.",
        "My mind is free of noise and calm.",
        "I choose calm and wise responses.",
        "My inner peace grows every day.",
        "I feel in complete emotional balance.",
        "Tranquility flows through my entire being.",
        "I live from a place of deep serenity.",
        "I release control and embrace peace.",
        "My heart beats calm and content.",
        "I am at peace with the past, present, and future.",
        "My mind is a serene and crystal-clear lake.",
        "Calm is my superpower.",
        "I feel safe, calm, and at peace.",
        "I choose thoughts that nurture my serenity.",
        "My peace does not depend on external circumstances.",
        "I live in a constant state of well-being.",
        "My soul breathes peace in every moment.",
        "I allow myself to rest in tranquility.",
        "Everything is resolved with calm and wisdom.",
        "My interior is a sanctuary of peace.",
        "I feel light, calm, and happy.",
        "Peace flows through every cell of my being.",
        "I live in total harmony with myself and with life.",
        "Every day I become the best version of myself.",
        "I attract experiences that make me grow.",
        "I fully trust my path and timing.",
        "I have everything necessary to succeed.",
        "My dreams materialize with ease.",
        "I am brave and take firm steps toward my goals.",
        "Success finds me because I go toward it.",
        "I learn with joy from every experience.",
        "My life improves in every area constantly.",
        "I am magnetic for perfect opportunities.",
        "I create extraordinary results with ease.",
        "I trust my intuition and my decisions.",
        "My life is a beautiful and exciting adventure.",
        "I open myself to receive all the good I deserve.",
        "Every day is a new opportunity to shine.",
        "I live with purpose, passion, and joy.",
        "Everything I need arrives at the perfect moment.",
        "I am a creative, powerful being full of talent.",
        "My goals are achieved with grace and flow.",
        "I feel fulfilled and deeply happy.",
        "The universe is always on my side.",
        "I live a full, authentic, and meaningful life.",
        "I attract healthy and enriching relationships.",
        "My positive energy transforms my reality.",
        "I am free to create the life of my dreams.",
        "Every challenge makes me stronger and wiser.",
        "My future is bright, abundant, and happy.",
        "I allow myself to dream big and achieve it.",
        "I live with gratitude and wonder every day.",
        "I am a magnet for everyday miracles.",
        "My life flows with ease and joy.",
        "I trust that everything works in my favor.",
        "I feel supported by the entire universe.",
        "I create beauty, love, and abundance wherever I go.",
        "My potential is unlimited and I am using it.",
        "{name}, you are infinitely valuable and loved exactly as you are.",
        "Every day {name} accepts yourself more and loves yourself more deeply.",
        "{name}, you deserve a life full of joy, love, and abundance.",
        "The universe always conspires in favor of {name}.",
        "{name}, your inner light shines brighter every day.",
        "{name}, you fully trust your intuition and your decisions.",
        "Everything {name} needs is already arriving in their life.",
        "{name}, you are strong, resilient, and capable of overcoming any challenge.",
        "Peace and calm permanently reside in {name}'s heart.",
        "{name}, you attract people and opportunities that lift you higher.",
        "Every morning {name} wakes up full of energy and gratitude.",
        "{name}, your self-esteem grows and strengthens with every breath.",
        "Success and prosperity naturally chase after {name}.",
        "{name}, you easily forgive yourself and release the entire past.",
        "Your body and mind are in perfect harmony, {name}.",
        "{name}, you are worthy of receiving unconditional love every day.",
        "Abundance flows to {name} in unexpected and wonderful ways.",
        "{name}, every step you take brings you closer to your most fulfilled version.",
        "Happiness is {name}'s natural state.",
        "{name}, you radiate confidence, charisma, and positive magnetism.",
        "Everything conspires so that {name} lives their best possible life.",
        "{name}, you allow yourself to dream big and watch those dreams come true.",
        "Health, vitality, and strength always accompany {name}.",
        "{name}, you are a unique, irreplaceable, and absolutely valuable being.",
        "Every challenge strengthens and makes {name} shine even brighter.",
        "{name}, you live in a permanent state of gratitude and wonder.",
        "{name}'s self-love is deep, solid, and unbreakable.",
        "{name}, you deserve and receive respect, affection, and admiration.",
        "{name}'s life improves in every aspect with each passing day.",
        "{name}, you are the highest and most authentic version of yourself."
    ]
}
