//
//  AffirmationCatalog.swift
//  Daily AI Affirmations
//
//  Created by Codex.
//

import Foundation

enum AffirmationCatalog {
    static let spanish: [String] = [
        "Hoy elijo la calma y la claridad.",
        "Confío en mi proceso paso a paso.",
        "Merezco descansar y recargar energía.",
        "Mi mente puede aprender algo nuevo hoy.",
        "Me permito avanzar a mi propio ritmo.",
        "Respiro profundo y suelto la tensión.",
        "Soy constante y eso me fortalece.",
        "Mi esfuerzo de hoy construye mi futuro.",
        "Tengo la capacidad de resolver lo importante.",
        "Atraigo oportunidades alineadas con mis valores.",
        "Mi creatividad fluye con facilidad.",
        "Hoy cuido mi cuerpo con cariño.",
        "Puedo pedir ayuda cuando la necesito.",
        "Soy amable conmigo misma/o.",
        "Cada paso pequeño cuenta.",
        "Mi enfoque crea resultados.",
        "Elijo pensamientos que me apoyan.",
        "Estoy presente y en paz.",
        "Mi voz merece ser escuchada.",
        "Acepto el progreso, no la perfección.",
        "Confío en mi intuición.",
        "Mi energía es valiosa y la administro bien.",
        "Soy capaz de adaptarme a los cambios.",
        "Me abro a nuevas posibilidades.",
        "Tengo disciplina y corazón.",
        "Mi paciencia es una fortaleza.",
        "Hoy honro mis límites.",
        "Mis decisiones reflejan mi bienestar.",
        "Me permito disfrutar el momento.",
        "Mi gratitud me abre caminos.",
        "Estoy aprendiendo y creciendo cada día.",
        "Soy suficiente tal como soy.",
        "Mi trabajo tiene propósito.",
        "Puedo comenzar de nuevo cuando lo necesite.",
        "Elijo la valentía sobre el miedo.",
        "Mi mente es clara y enfocada.",
        "Doy lo mejor de mí con tranquilidad.",
        "Mis ideas son valiosas.",
        "Mi corazón guía mis acciones.",
        "Confío en mi capacidad de crear hábitos sanos.",
        "Hoy me trato con respeto.",
        "Soy resiliente y puedo con esto.",
        "Merezco relaciones que me cuiden.",
        "Mi paz interior es mi prioridad.",
        "Puedo lograr cosas importantes con constancia.",
        "Acepto lo que no puedo controlar.",
        "Elijo una actitud abierta y positiva.",
        "Mi descanso también es productividad.",
        "Mi voz interna es amable.",
        "Hoy elijo el equilibrio.",
        "Me permito celebrar mis avances.",
        "Estoy rodeada/o de apoyo.",
        "Mi enfoque es gentil y firme.",
        "Soy capaz de aprender de mis errores.",
        "Mi tiempo es valioso.",
        "Hoy me doy permiso de brillar.",
        "Mi curiosidad me impulsa.",
        "Soy flexible y adaptable.",
        "Puedo concentrarme en lo esencial.",
        "La calma me acompaña.",
        "Confío en el ritmo natural de la vida.",
        "Mi bienestar es una elección diaria.",
        "Estoy haciendo lo correcto para mí.",
        "Mi creatividad encuentra soluciones.",
        "Elijo palabras que me elevan.",
        "Soy fuerte y serena/o.",
        "Mi corazón está en paz.",
        "Puedo terminar lo que empiezo.",
        "Hoy reconozco mi valor.",
        "Mi trabajo mejora con práctica.",
        "Merezco cosas buenas.",
        "Estoy en el camino correcto.",
        "Mi amabilidad crea conexiones.",
        "Elijo cuidar mi energía.",
        "Hoy mi mente está tranquila.",
        "Mis sueños merecen mi atención.",
        "Me permito avanzar con confianza.",
        "Soy digno/a de éxito.",
        "Mi presencia es un regalo.",
        "Puedo tomar decisiones sabias.",
        "Hoy elijo la gratitud.",
        "Mi esfuerzo está dando frutos.",
        "Elijo aprender en lugar de juzgar.",
        "Mi equilibrio emocional crece.",
        "Confío en mis habilidades.",
        "Mi futuro se construye con amor.",
        "Hoy suelto lo que me pesa.",
        "Soy luz para mí y para otros.",
        "Mi mente es un lugar seguro.",
        "Merezco sentirme en paz.",
        "Hoy, {name}, eliges cuidarte.",
        "{name}, tu constancia te llevará lejos.",
        "Respira, {name}, lo estás haciendo bien.",
        "Hoy, {name}, confías en tu camino.",
        "{name}, tu voz importa.",
        "Tu calma inspira, {name}.",
        "{name}, mereces descanso y alegría.",
        "Paso a paso, {name}, estás creciendo.",
        "{name}, tu esfuerzo cuenta.",
        "{name}, hoy eliges tu bienestar."
    ]

    static let english: [String] = [
        "Today I choose calm and clarity.",
        "I trust my process step by step.",
        "I deserve rest and renewal.",
        "My mind can learn something new today.",
        "I allow myself to move at my own pace.",
        "I breathe deeply and release tension.",
        "Consistency strengthens me.",
        "My effort today builds my future.",
        "I can handle what matters.",
        "Opportunities aligned with my values find me.",
        "My creativity flows with ease.",
        "Today I care for my body with kindness.",
        "I can ask for help when I need it.",
        "I am gentle with myself.",
        "Every small step counts.",
        "My focus creates results.",
        "I choose thoughts that support me.",
        "I am present and at peace.",
        "My voice deserves to be heard.",
        "I honor progress over perfection.",
        "I trust my intuition.",
        "My energy is valuable and I use it wisely.",
        "I adapt to change with grace.",
        "I open myself to new possibilities.",
        "I have discipline and heart.",
        "My patience is a strength.",
        "Today I honor my boundaries.",
        "My choices reflect my well-being.",
        "I allow myself to enjoy the moment.",
        "Gratitude opens doors for me.",
        "I am learning and growing every day.",
        "I am enough exactly as I am.",
        "My work has purpose.",
        "I can begin again whenever I need to.",
        "I choose courage over fear.",
        "My mind is clear and focused.",
        "I give my best with ease.",
        "My ideas are valuable.",
        "My heart guides my actions.",
        "I trust my ability to build healthy habits.",
        "Today I treat myself with respect.",
        "I am resilient and I can do this.",
        "I deserve relationships that care for me.",
        "My inner peace is my priority.",
        "I can achieve important things with consistency.",
        "I accept what I cannot control.",
        "I choose an open and positive attitude.",
        "My rest is also productive.",
        "My inner voice is kind.",
        "Today I choose balance.",
        "I allow myself to celebrate my progress.",
        "I am supported.",
        "My focus is gentle and steady.",
        "I can learn from my mistakes.",
        "My time is valuable.",
        "Today I give myself permission to shine.",
        "My curiosity moves me forward.",
        "I am flexible and adaptable.",
        "I can concentrate on what matters most.",
        "Calmness is with me.",
        "I trust the natural rhythm of life.",
        "My well-being is a daily choice.",
        "I am doing what is right for me.",
        "My creativity finds solutions.",
        "I choose words that lift me up.",
        "I am strong and serene.",
        "My heart is at peace.",
        "I can finish what I start.",
        "Today I recognize my worth.",
        "My work improves with practice.",
        "I deserve good things.",
        "I am on the right path.",
        "My kindness creates connection.",
        "I choose to protect my energy.",
        "Today my mind is calm.",
        "My dreams deserve my attention.",
        "I allow myself to move forward with confidence.",
        "I am worthy of success.",
        "My presence is a gift.",
        "I can make wise decisions.",
        "Today I choose gratitude.",
        "My effort is paying off.",
        "I choose to learn instead of judge.",
        "My emotional balance grows.",
        "I trust my abilities.",
        "My future is built with love.",
        "Today I release what weighs me down.",
        "I am light for myself and others.",
        "My mind is a safe place.",
        "I deserve to feel at peace.",
        "Today, {name}, you choose to care for yourself.",
        "{name}, your consistency will take you far.",
        "Breathe, {name}, you are doing well.",
        "Today, {name}, you trust your path.",
        "{name}, your voice matters.",
        "Your calm inspires, {name}.",
        "{name}, you deserve rest and joy.",
        "Step by step, {name}, you are growing.",
        "{name}, your effort counts.",
        "{name}, today you choose your well-being."
    ]
}
